mindmap
  root[C3D]
    Header
      points info
      analogs info
    Parameters
      POINT
        LABELS
        UNITS
        RATE
      ANALOG
        LABELS
        UNITS
        RATE
      FORCE_PLATFORM
        TYPE
        CORNERS
        ORIGIN
        CHANNEL
        CAL_MATRIX
    Data
      points
        row one X
        row two Y
        row three Z
        row four residual
      analogs
        channels by time
