[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "biomech-setup"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
  "pandas",
  "ezc3d"
]

[project.scripts]
biomech-setup = "biomech_setup.cli:main"
